# Generated by Django 3.0.5 on 2020-04-02 13:01

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('population', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('cms_id', models.CharField(max_length=6, blank=True, db_index=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, geography=True, srid=4326)),
                ('emergency_services', models.BooleanField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.County')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(db_index=True, max_length=2)),
                ('population', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('med_beds_capacity', models.IntegerField(blank=True)),
                ('med_beds_used', models.IntegerField(blank=True)),
                ('icu_beds_capacity', models.IntegerField(blank=True)),
                ('icu_beds_used', models.IntegerField(blank=True)),
                ('ventilators_capacity', models.IntegerField(blank=True)),
                ('ventilators_used', models.IntegerField(blank=True)),
                ('c19_patients', models.IntegerField(blank=True)),
                ('c19_vent_patients', models.IntegerField(blank=True)),
                ('c19_hospital_onset_patients', models.IntegerField(blank=True)),
                ('c19_awaiting_bed', models.IntegerField(blank=True)),
                ('c19_vent_awaiting_bed', models.IntegerField(blank=True)),
                ('c19_deaths', models.IntegerField(blank=True)),
                ('supply_n95respirators', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('supply_facemasks', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('supply_gloves', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('supply_faceshields', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('supply_gowns', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('staffing_physicians', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('staffing_nurses', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('staffing_ancillady', models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')])),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Facility')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.State'),
        ),
    ]
