# Generated by Django 3.0.5 on 2020-04-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_load_hospital_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitymetrics',
            old_name='staffing_ancillady',
            new_name='staffing_ancillary',
        ),
    ]
