# Generated by Django 3.0.5 on 2020-04-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200403_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitymetrics',
            name='c19_awaiting_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='c19_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='c19_hospital_onset_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='c19_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='c19_vent_awaiting_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='c19_vent_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
