# Generated by Django 3.0.5 on 2020-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200403_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitymetrics',
            name='staffing_ancillary',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='staffing_nurses',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='staffing_physicians',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='supply_facemasks',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='supply_faceshields',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='supply_gloves',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='supply_gowns',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='facilitymetrics',
            name='supply_n95respirators',
            field=models.IntegerField(choices=[(0, 'Covered'), (1, 'Concerned'), (2, 'Critical')], null=True),
        ),
    ]
